import type { SymbolicatorInput } from '../src/dev-server/symbolicator/types.js';

const exampleStack: SymbolicatorInput = {
  stack: [
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'Root',
      arguments: [],
      lineNumber: 592060,
      column: 52,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'renderWithHooks2',
      arguments: [],
      lineNumber: 97915,
      column: 36,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'mountIndeterminateComponent2',
      arguments: [],
      lineNumber: 99600,
      column: 38,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'beginWork$12',
      arguments: [],
      lineNumber: 106557,
      column: 32,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'performUnitOfWork2',
      arguments: [],
      lineNumber: 102675,
      column: 32,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'workLoopSync2',
      arguments: [],
      lineNumber: 102624,
      column: 31,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'renderRootSync2',
      arguments: [],
      lineNumber: 102604,
      column: 28,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'performSyncWorkOnRoot2',
      arguments: [],
      lineNumber: 102408,
      column: 43,
    },
    {
      file: '[native code]',
      methodName: 'performSyncWorkOnRoot2',
      arguments: [],
      lineNumber: null,
      column: null,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'flushSyncCallbacks',
      arguments: [],
      lineNumber: 105091,
      column: 39,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'flushSyncCallbacksOnlyInLegacyMode2',
      arguments: [],
      lineNumber: 95859,
      column: 32,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'scheduleUpdateOnFiber2',
      arguments: [],
      lineNumber: 102221,
      column: 52,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'updateContainer2',
      arguments: [],
      lineNumber: 103959,
      column: 44,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'render12',
      arguments: [],
      lineNumber: 104121,
      column: 27,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'renderApplication',
      arguments: [],
      lineNumber: 85789,
      column: 38,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'run',
      arguments: [],
      lineNumber: 89245,
      column: 31,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'runApplication',
      arguments: [],
      lineNumber: 89295,
      column: 31,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: '__callFunction',
      arguments: [],
      lineNumber: 17888,
      column: 41,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: '<unknown>',
      arguments: [],
      lineNumber: 17629,
      column: 36,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: '__guard',
      arguments: [],
      lineNumber: 17844,
      column: 20,
    },
    {
      file: 'http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.tgv',
      methodName: 'callFunctionReturnFlushedQueue',
      arguments: [],
      lineNumber: 17628,
      column: 26,
    },
    {
      file: '[native code]',
      methodName: 'callFunctionReturnFlushedQueue',
      arguments: [],
      lineNumber: null,
      column: null,
    },
  ],
};
